version: 0.2
env:
    secrets-manager:
      TOKEN: firstsecret:tokenforsonar
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=daya_javaproject11 -Dsonar.organization=daya -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN 
